name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4  # ✅ Ensure latest version

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3  # ✅ Try v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2  # ✅ Use correct Terraform setup
      with:
        terraform_version: 1.7.2  # Change version if needed

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform
      run: terraform validate

    - name: Plan Terraform Changes
      run: terraform plan

    - name: Apply Terraform Changes
      run: terraform apply -auto-approve
